# Polynomial Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv(r"D:\ml\resorces\Machine Learning-A-Z-Codes-Datasets\Machine Learning A-Z (Codes and Datasets)\132 - Machine-Learning-A-Z-Model-Selection\Machine Learning A-Z (Model Selection)\Regression\Data.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
X, y

(array([[  14.96,   41.76, 1024.07,   73.17],
        [  25.18,   62.96, 1020.04,   59.08],
        [   5.11,   39.4 , 1012.16,   92.14],
        ...,
        [  31.32,   74.33, 1012.92,   36.48],
        [  24.48,   69.45, 1013.86,   62.39],
        [  21.6 ,   62.52, 1017.23,   67.87]]),
 array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28]))

## Splitting the dataset into the Training set and Test set

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0)

X_train, X_test, y_train, y_test

(array([[  11.22,   43.13, 1017.24,   80.9 ],
        [  13.67,   54.3 , 1015.92,   75.42],
        [  32.84,   77.95, 1014.68,   45.8 ],
        ...,
        [  16.81,   38.52, 1018.26,   75.21],
        [  12.8 ,   41.16, 1022.43,   86.19],
        [  32.32,   67.9 , 1006.08,   37.93]]),
 array([[  28.66,   77.95, 1009.56,   69.07],
        [  17.48,   49.39, 1021.51,   84.53],
        [  14.86,   43.14, 1019.21,   99.14],
        ...,
        [  12.24,   44.92, 1023.74,   88.21],
        [  27.28,   47.93, 1003.46,   59.22],
        [  17.28,   39.99, 1007.09,   74.25]]),
 array([473.93, 467.87, 431.97, ..., 459.01, 462.72, 428.12]),
 array([431.23, 460.01, 461.14, ..., 473.26, 438.  , 463.28]))

## Training the Polynomial Regression model on the Training set

In [4]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree=4)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

LinearRegression()

In [5]:
X_poly

array([[1.00000000e+00, 1.12200000e+01, 4.31300000e+01, ...,
        6.77242028e+09, 5.38603280e+08, 4.28345379e+07],
       [1.00000000e+00, 1.36700000e+01, 5.43000000e+01, ...,
        5.87072958e+09, 4.35831980e+08, 3.23553508e+07],
       [1.00000000e+00, 3.28400000e+01, 7.79500000e+01, ...,
        2.15967876e+09, 9.74822477e+07, 4.40009357e+06],
       ...,
       [1.00000000e+00, 1.68100000e+01, 3.85200000e+01, ...,
        5.86500714e+09, 4.33197009e+08, 3.19964912e+07],
       [1.00000000e+00, 1.28000000e+01, 4.11600000e+01, ...,
        7.76570573e+09, 6.54642544e+08, 5.51858229e+07],
       [1.00000000e+00, 3.23200000e+01, 6.79000000e+01, ...,
        1.45623249e+09, 5.49010997e+07, 2.06981424e+06]])

## Predicting the Test set results

In [6]:
y_pred = regressor.predict(poly_reg.transform(X_test))
# np.set_printoptions(precision=2)
# print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

## Evaluating the Model Performance

In [7]:
from sklearn.metrics import r2_score
r2_score(y_test, regressor.predict(poly_reg.transform(X_test)))

0.9458193007079888