In [30]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [31]:
data=pd.read_csv(r'Social_Network_Ads.csv')

x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [32]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

x=scaler.fit_transform(x)

x

array([[-1.78179743, -1.49004624],
       [-0.25358736, -1.46068138],
       [-1.11320552, -0.78528968],
       [-1.01769239, -0.37418169],
       [-1.78179743,  0.18375059],
       [-1.01769239, -0.34481683],
       [-1.01769239,  0.41866944],
       [-0.54012675,  2.35674998],
       [-1.20871865, -1.07893824],
       [-0.25358736, -0.13926283],
       [-1.11320552,  0.30121002],
       [-1.11320552, -0.52100597],
       [-1.6862843 ,  0.47739916],
       [-0.54012675, -1.51941109],
       [-1.87731056,  0.35993973],
       [-0.82666613,  0.30121002],
       [ 0.89257019, -1.3138571 ],
       [ 0.70154394, -1.28449224],
       [ 0.79705706, -1.22576253],
       [ 0.98808332, -1.19639767],
       [ 0.70154394, -1.40195167],
       [ 0.89257019, -0.60910054],
       [ 0.98808332, -0.84401939],
       [ 0.70154394, -1.40195167],
       [ 0.79705706, -1.37258681],
       [ 0.89257019, -1.46068138],
       [ 1.08359645, -1.22576253],
       [ 0.89257019, -1.16703281],
       [-0.82666613,

In [33]:
from sklearn.model_selection import train_test_split

xTrain,Xtest,Ytrain,Ytest=train_test_split(x,y,test_size=.2,random_state=0)
xTrain,Xtest,Ytrain,Ytest

(array([[ 1.94321462,  2.18056084],
        [ 2.03872775,  0.38930459],
        [-1.30423178, -0.4329114 ],
        [-1.11320552, -1.02020853],
        [ 1.94321462, -0.93211396],
        [ 0.41500455,  0.30121002],
        [ 0.22397829,  0.15438573],
        [ 2.03872775,  1.76945285],
        [ 0.79705706, -0.84401939],
        [ 0.31949142, -0.28608712],
        [ 0.41500455, -0.16862769],
        [-0.0625611 ,  2.23929055],
        [-1.39974491, -0.63846539],
        [-1.20871865, -1.07893824],
        [-1.30423178,  0.41866944],
        [-1.01769239,  0.77104772],
        [-1.39974491, -0.19799255],
        [ 0.98808332, -1.07893824],
        [ 0.98808332,  0.59485858],
        [ 0.41500455,  1.00596657],
        [ 0.60603081, -0.9027491 ],
        [-0.54012675,  1.47580428],
        [ 0.03295203, -0.57973568],
        [-0.54012675,  1.91627713],
        [ 1.37013584, -1.43131652],
        [ 1.46564897,  1.00596657],
        [ 0.12846516, -0.81465453],
        [ 0.03295203, -0.256

In [37]:
from sklearn.linear_model import LogisticRegression
regressor=LogisticRegression()

regressor.fit(xTrain,Ytrain)


LogisticRegression()

In [35]:

np.concatenate((Ytest.reshape(-1,1),regressor.predict(Xtest).reshape(-1,1)),1)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [1, 1],
       [0,

In [38]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(Ytest,regressor.predict(Xtest).reshape(-1,1))
accuracy_score(Ytest,regressor.predict(Xtest).reshape(-1,1))

0.925