In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv(r"D:\ml\resorces\Machine Learning-A-Z-Codes-Datasets\Machine Learning A-Z (Codes and Datasets)\132 - Machine-Learning-A-Z-Model-Selection\Machine Learning A-Z (Model Selection)\Regression\Data.csv")
data

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [3]:
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

x, y

(array([[  14.96,   41.76, 1024.07,   73.17],
        [  25.18,   62.96, 1020.04,   59.08],
        [   5.11,   39.4 , 1012.16,   92.14],
        ...,
        [  31.32,   74.33, 1012.92,   36.48],
        [  24.48,   69.45, 1013.86,   62.39],
        [  21.6 ,   62.52, 1017.23,   67.87]]),
 array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28]))

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
x

array([[-0.62951938, -0.98729659,  1.8204884 , -0.00951935],
       [ 0.74190911,  0.68104512,  1.1418628 , -0.97462052],
       [-1.95129733, -1.17301765, -0.18507756,  1.2898397 ],
       ...,
       [ 1.56583973,  1.57581141, -0.05709854, -2.52261812],
       [ 0.64797565,  1.19177803,  0.1011913 , -0.74790051],
       [ 0.26150656,  0.64641916,  0.66867722, -0.37254534]])

In [5]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, random_state=0, test_size=.1)

x_test, y_test, x_train, y_train

(array([[ 1.20889258e+00,  1.86068863e+00, -6.22900526e-01,
         -2.90350777e-01],
        [-2.91358934e-01, -3.86850962e-01,  1.38940117e+00,
          7.68589180e-01],
        [-6.42938450e-01, -8.78696985e-01,  1.00209624e+00,
          1.76930799e+00],
        ...,
        [ 7.59353892e-01,  1.06980022e+00, -1.16512743e+00,
         -3.60901111e-01],
        [ 2.39891040e-02, -6.27658775e-01,  1.83916338e-03,
          1.58163040e+00],
        [ 7.78140583e-01,  7.44001415e-01, -5.55543148e-01,
         -3.78709933e-01]]),
 array([431.23, 460.01, 461.14, 445.9 , 451.29, 432.68, 477.5 , 459.68,
        477.5 , 444.99, 444.37, 437.04, 442.34, 440.74, 436.55, 460.24,
        448.66, 432.94, 452.82, 432.2 , 430.96, 434.65, 473.56, 434.47,
        450.92, 452.82, 485.94, 435.47, 448.96, 465.89, 482.52, 465.05,
        475.51, 466.71, 472.42, 434.64, 467.97, 481.86, 437.72, 470.49,
        449.04, 468.15, 457.94, 486.4 , 443.52, 442.23, 430.61, 439.72,
        467.98, 433.36, 448.74,

In [6]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [7]:
regressor.predict(x_test)

array([431.47530915, 458.55620422, 462.74382942, 448.60132846,
       457.88121879, 429.71532437, 473.05138414, 456.50287382,
       474.33946253, 446.31817648, 441.95521058, 441.50129283,
       444.70878689, 440.8617238 , 438.45854486, 454.28281181,
       444.89830329, 437.39167132, 451.33057445, 427.4513763 ,
       425.41255419, 431.84421994, 474.12547777, 439.79248433,
       447.90634715, 452.49225989, 481.67246311, 444.62061537,
       451.90744163, 466.60166352, 477.13802186, 461.89415454,
       473.90355353, 468.47795614, 469.5773357 , 433.75334443,
       466.38485711, 479.91974692, 433.80459   , 472.0683349 ,
       446.19057519, 466.38674205, 456.93135066, 479.73239051,
       443.63766648, 439.87754083, 433.1718293 , 438.24279747,
       470.21980845, 440.22491468, 457.86885182, 463.68598995,
       440.77508178, 467.50576542, 463.43226094, 443.30145264,
       483.71719752, 481.77734637, 459.98908555, 486.0212349 ,
       439.04012805, 449.26592903, 467.68226202, 448.02

In [8]:
from sklearn.metrics import r2_score

r2_score(y_test, regressor.predict(x_test))

0.9365341601931816