In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv(r"D:\ml\resorces\Machine Learning-A-Z-Codes-Datasets\Machine Learning A-Z (Codes and Datasets)\132 - Machine-Learning-A-Z-Model-Selection\Machine Learning A-Z (Model Selection)\Regression\Data.csv")
data

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [3]:
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

x, y

(array([[  14.96,   41.76, 1024.07,   73.17],
        [  25.18,   62.96, 1020.04,   59.08],
        [   5.11,   39.4 , 1012.16,   92.14],
        ...,
        [  31.32,   74.33, 1012.92,   36.48],
        [  24.48,   69.45, 1013.86,   62.39],
        [  21.6 ,   62.52, 1017.23,   67.87]]),
 array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28]))

In [4]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, random_state=0, test_size=.1)

x_test, y_test, x_train, y_train

(array([[  28.66,   77.95, 1009.56,   69.07],
        [  17.48,   49.39, 1021.51,   84.53],
        [  14.86,   43.14, 1019.21,   99.14],
        ...,
        [  25.31,   67.9 , 1006.34,   68.04],
        [  19.83,   46.33, 1013.27,   96.4 ],
        [  25.45,   63.76, 1009.96,   67.78]]),
 array([431.23, 460.01, 461.14, 445.9 , 451.29, 432.68, 477.5 , 459.68,
        477.5 , 444.99, 444.37, 437.04, 442.34, 440.74, 436.55, 460.24,
        448.66, 432.94, 452.82, 432.2 , 430.96, 434.65, 473.56, 434.47,
        450.92, 452.82, 485.94, 435.47, 448.96, 465.89, 482.52, 465.05,
        475.51, 466.71, 472.42, 434.64, 467.97, 481.86, 437.72, 470.49,
        449.04, 468.15, 457.94, 486.4 , 443.52, 442.23, 430.61, 439.72,
        467.98, 433.36, 448.74, 464.39, 443.06, 470.23, 467.21, 449.1 ,
        487.33, 473.73, 461.96, 483.12, 433.81, 444.05, 457.11, 446.56,
        440.32, 489.  , 427.77, 439.94, 481.29, 471.23, 446.38, 471.6 ,
        461.07, 480.38, 460.54, 455.6 , 444.68, 471.8 , 480.9

In [5]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=10, random_state=0)
regressor.fit(x_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [6]:
from sklearn.metrics import r2_score
r2_score(y_test, regressor.predict(x_test))

0.9648417581025929