In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv(r"D:\ml\resorces\Machine Learning-A-Z-Codes-Datasets\Machine Learning A-Z (Codes and Datasets)\132 - Machine-Learning-A-Z-Model-Selection\Machine Learning A-Z (Model Selection)\Regression\Data.csv")
data

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [3]:
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values
y = y.reshape(-1, 1)
x, y

(array([[  14.96,   41.76, 1024.07,   73.17],
        [  25.18,   62.96, 1020.04,   59.08],
        [   5.11,   39.4 , 1012.16,   92.14],
        ...,
        [  31.32,   74.33, 1012.92,   36.48],
        [  24.48,   69.45, 1013.86,   62.39],
        [  21.6 ,   62.52, 1017.23,   67.87]]),
 array([[463.26],
        [444.37],
        [488.56],
        ...,
        [429.57],
        [435.74],
        [453.28]]))

In [4]:
from sklearn.preprocessing import StandardScaler

sc_x = StandardScaler()
sc_y = StandardScaler()

x_scaled = sc_x.fit_transform(x)
y_scaled = sc_y.fit_transform(y)

x_scaled, y_scaled

(array([[-0.62951938, -0.98729659,  1.8204884 , -0.00951935],
        [ 0.74190911,  0.68104512,  1.1418628 , -0.97462052],
        [-1.95129733, -1.17301765, -0.18507756,  1.2898397 ],
        ...,
        [ 1.56583973,  1.57581141, -0.05709854, -2.52261812],
        [ 0.64797565,  1.19177803,  0.1011913 , -0.74790051],
        [ 0.26150656,  0.64641916,  0.66867722, -0.37254534]]),
 array([[ 0.52120807],
        [-0.58566442],
        [ 2.00367889],
        ...,
        [-1.45288056],
        [-1.09134518],
        [-0.06357687]]))

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x_scaled, y_scaled, test_size=.1, random_state=0)
x_train, x_test, y_train, y_test

(array([[ 1.19547352,  1.56715492, -0.9782107 , -0.25404818],
        [ 0.60637655, -0.46397242, -0.80813332,  0.19733696],
        [-0.23634077, -1.11635698, -0.21370445,  0.21994047],
        ...,
        [-0.38126667, -1.24226957,  0.84212247,  0.1302114 ],
        [-0.9193712 , -1.03451381,  1.54432314,  0.88229166],
        [ 1.70003038,  1.06980022, -1.20890972, -2.42329969]]),
 array([[ 1.20889258e+00,  1.86068863e+00, -6.22900526e-01,
         -2.90350777e-01],
        [-2.91358934e-01, -3.86850962e-01,  1.38940117e+00,
          7.68589180e-01],
        [-6.42938450e-01, -8.78696985e-01,  1.00209624e+00,
          1.76930799e+00],
        ...,
        [ 7.59353892e-01,  1.06980022e+00, -1.16512743e+00,
         -3.60901111e-01],
        [ 2.39891040e-02, -6.27658775e-01,  1.83916338e-03,
          1.58163040e+00],
        [ 7.78140583e-01,  7.44001415e-01, -5.55543148e-01,
         -3.78709933e-01]]),
 array([[-1.16166   ],
        [-0.68820687],
        [-0.15088444],
       

In [6]:
from sklearn.svm import SVR

regressor = SVR(kernel='rbf')

regressor.fit(x_train, y_train)

C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [7]:
from sklearn.metrics import r2_score
r2_score(sc_y.inverse_transform(y_test), sc_y.inverse_transform(
    regressor.predict(x_test).reshape(-1, 1)))

0.9524350644438118