In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data=pd.read_csv(r"Social_Network_Ads.csv")

x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [3]:
from sklearn.preprocessing import StandardScaler

sc_x=StandardScaler()

x_scaled=sc_x.fit_transform(x)

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=.25,random_state=0)

x_train, x_test,y_train,y_test

(array([[ 0.60603081, -0.9027491 ],
        [-0.54012675,  1.47580428],
        [ 0.03295203, -0.57973568],
        [-0.54012675,  1.91627713],
        [ 1.37013584, -1.43131652],
        [ 1.46564897,  1.00596657],
        [ 0.12846516, -0.81465453],
        [ 0.03295203, -0.25672226],
        [-0.15807423, -0.57973568],
        [-0.15807423, -0.19799255],
        [-0.25358736, -1.3138571 ],
        [-0.25358736, -0.57973568],
        [ 0.41500455,  0.09565602],
        [ 0.89257019, -0.60910054],
        [ 2.03872775, -1.19639767],
        [ 1.08359645, -0.13926283],
        [ 0.70154394,  1.7988177 ],
        [-0.63563988,  0.56549373],
        [ 0.79705706,  0.35993973],
        [ 0.89257019, -0.55037082],
        [-1.11320552, -1.60750566],
        [ 2.13424088,  0.94723686],
        [ 0.03295203,  1.24088543],
        [ 0.22397829,  1.09406114],
        [ 0.41500455, -0.49164111],
        [-0.25358736, -0.31545197],
        [ 0.98808332, -0.84401939],
        [ 0.98808332,  1.886

In [5]:
from sklearn.svm import SVC

classifier=SVC()

classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [6]:
np.concatenate((y_test.reshape(-1,1),y_pred.reshape(-1,1)),axis=1)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0,

In [7]:
from sklearn.metrics import confusion_matrix,accuracy_score

cm= confusion_matrix(y_test.reshape(-1,1),y_pred.reshape(-1,1))

print(cm)

accuracy_score(y_test,y_pred)

[[64  4]
 [ 3 29]]


0.93