In [38]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [39]:
#import data

startUps=pd.read_csv(r"D:\ml\resorces\Machine Learning-A-Z-Codes-Datasets\Machine Learning A-Z (Codes and Datasets)\Part 2 - Regression\Section 5 - Multiple Linear Regression\Python\50_Startups.csv")
startUps['isNewYork']=(startUps['State']=='New York').astype(int)
startUps['isCalifornia']=(startUps['State']=='California').astype(int)
p=startUps['Profit']
startUps=startUps.drop(['State','Profit'],axis=1)
startUps["Profit"]=p


startUps

R&D Spend  Administration  Marketing Spend  isNewYork  isCalifornia  \
0   165349.20       136897.80        471784.10          1             0   
1   162597.70       151377.59        443898.53          0             1   
2   153441.51       101145.55        407934.54          0             0   
3   144372.41       118671.85        383199.62          1             0   
4   142107.34        91391.77        366168.42          0             0   
5   131876.90        99814.71        362861.36          1             0   
6   134615.46       147198.87        127716.82          0             1   
7   130298.13       145530.06        323876.68          0             0   
8   120542.52       148718.95        311613.29          1             0   
9   123334.88       108679.17        304981.62          0             1   
10  101913.08       110594.11        229160.95          0             0   
11  100671.96        91790.61        249744.55          0             1   
12   93863.75       127320.38        249839.44          0             0   
13   91992.39       135495.07        252664.93          0             1   
14  119943.24       156547.42        256512.92          0             0   
15  114523.61       122616.84        261776.23          1             0   
16   78013.11       121597.55        264346.06          0             1   
17   94657.16       145077.58        282574.31          1             0   
18   91749.16       114175.79        294919.57          0             0   
19   86419.70       153514.11             0.00          1             0   
20   76253.86       113867.30        298664.47          0             1   
21   78389.47       153773.43        299737.29          1             0   
22   73994.56       122782.75        303319.26          0             0   
23   67532.53       105751.03        304768.73          0             0   
24   77044.01        99281.34        140574.81          1             0   
25   64664.71       139553.16        137962.62          0             1   
26   75328.87       144135.98        134050.07          0             0   
27   72107.60       127864.55        353183.81          1             0   
28   66051.52       182645.56        118148.20          0             0   
29   65605.48       153032.06        107138.38          1             0   
30   61994.48       115641.28         91131.24          0             0   
31   61136.38       152701.92         88218.23          1             0   
32   63408.86       129219.61         46085.25          0             1   
33   55493.95       103057.49        214634.81          0             0   
34   46426.07       157693.92        210797.67          0             1   
35   46014.02        85047.44        205517.64          1             0   
36   28663.76       127056.21        201126.82          0             0   
37   44069.95        51283.14        197029.42          0             1   
38   20229.59        65947.93        185265.10          1             0   
39   38558.51        82982.09        174999.30          0             1   
40   28754.33       118546.05        172795.67          0             1   
41   27892.92        84710.77        164470.71          0             0   
42   23640.93        96189.63        148001.11          0             1   
43   15505.73       127382.30         35534.17          1             0   
44   22177.74       154806.14         28334.72          0             1   
45    1000.23       124153.04          1903.93          1             0   
46    1315.46       115816.21        297114.46          0             0   
47       0.00       135426.92             0.00          0             1   
48     542.05        51743.15             0.00          1             0   
49       0.00       116983.80         45173.06          0             1   

       Profit  
0   192261.83  
1   191792.06  
2   191050.39  
3   182901.99  
4   166187.94  
5   156991.12  
6   156122.51  
7   155752.60  
8   152211.77  
9   149759.96  
10

In [40]:
#import data

x=startUps.iloc[:, :-1].values
y=startUps.iloc[:, -1].values
x



array([[1.65e+05, 1.37e+05, 4.72e+05, 1.00e+00, 0.00e+00],
       [1.63e+05, 1.51e+05, 4.44e+05, 0.00e+00, 1.00e+00],
       [1.53e+05, 1.01e+05, 4.08e+05, 0.00e+00, 0.00e+00],
       [1.44e+05, 1.19e+05, 3.83e+05, 1.00e+00, 0.00e+00],
       [1.42e+05, 9.14e+04, 3.66e+05, 0.00e+00, 0.00e+00],
       [1.32e+05, 9.98e+04, 3.63e+05, 1.00e+00, 0.00e+00],
       [1.35e+05, 1.47e+05, 1.28e+05, 0.00e+00, 1.00e+00],
       [1.30e+05, 1.46e+05, 3.24e+05, 0.00e+00, 0.00e+00],
       [1.21e+05, 1.49e+05, 3.12e+05, 1.00e+00, 0.00e+00],
       [1.23e+05, 1.09e+05, 3.05e+05, 0.00e+00, 1.00e+00],
       [1.02e+05, 1.11e+05, 2.29e+05, 0.00e+00, 0.00e+00],
       [1.01e+05, 9.18e+04, 2.50e+05, 0.00e+00, 1.00e+00],
       [9.39e+04, 1.27e+05, 2.50e+05, 0.00e+00, 0.00e+00],
       [9.20e+04, 1.35e+05, 2.53e+05, 0.00e+00, 1.00e+00],
       [1.20e+05, 1.57e+05, 2.57e+05, 0.00e+00, 0.00e+00],
       [1.15e+05, 1.23e+05, 2.62e+05, 1.00e+00, 0.00e+00],
       [7.80e+04, 1.22e+05, 2.64e+05, 0.00e+00, 1.00e+00

In [41]:
#standardization of y

from sklearn.preprocessing import MinMaxScaler

scaller=MinMaxScaler()
x=scaller.fit_transform(x)
x

array([[1.  , 0.65, 1.  , 1.  , 0.  ],
       [0.98, 0.76, 0.94, 0.  , 1.  ],
       [0.93, 0.38, 0.86, 0.  , 0.  ],
       [0.87, 0.51, 0.81, 1.  , 0.  ],
       [0.86, 0.31, 0.78, 0.  , 0.  ],
       [0.8 , 0.37, 0.77, 1.  , 0.  ],
       [0.81, 0.73, 0.27, 0.  , 1.  ],
       [0.79, 0.72, 0.69, 0.  , 0.  ],
       [0.73, 0.74, 0.66, 1.  , 0.  ],
       [0.75, 0.44, 0.65, 0.  , 1.  ],
       [0.62, 0.45, 0.49, 0.  , 0.  ],
       [0.61, 0.31, 0.53, 0.  , 1.  ],
       [0.57, 0.58, 0.53, 0.  , 0.  ],
       [0.56, 0.64, 0.54, 0.  , 1.  ],
       [0.73, 0.8 , 0.54, 0.  , 0.  ],
       [0.69, 0.54, 0.55, 1.  , 0.  ],
       [0.47, 0.54, 0.56, 0.  , 1.  ],
       [0.57, 0.71, 0.6 , 1.  , 0.  ],
       [0.55, 0.48, 0.63, 0.  , 0.  ],
       [0.52, 0.78, 0.  , 1.  , 0.  ],
       [0.46, 0.48, 0.63, 0.  , 1.  ],
       [0.47, 0.78, 0.64, 1.  , 0.  ],
       [0.45, 0.54, 0.64, 0.  , 0.  ],
       [0.41, 0.41, 0.65, 0.  , 0.  ],
       [0.47, 0.37, 0.3 , 1.  , 0.  ],
       [0.39, 0.67, 0.29,

In [42]:

#split data into train and test set

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=0)

x_train

array([[0.34, 0.39, 0.45, 0.  , 0.  ],
       [0.28, 0.26, 0.44, 1.  , 0.  ],
       [0.46, 0.71, 0.28, 0.  , 0.  ],
       [0.28, 0.81, 0.45, 0.  , 1.  ],
       [0.55, 0.48, 0.63, 0.  , 0.  ],
       [0.79, 0.72, 0.69, 0.  , 0.  ],
       [0.73, 0.8 , 0.54, 0.  , 0.  ],
       [0.01, 0.55, 0.  , 1.  , 0.  ],
       [0.  , 0.  , 0.  , 1.  , 0.  ],
       [0.4 , 0.77, 0.23, 1.  , 0.  ],
       [0.69, 0.54, 0.55, 1.  , 0.  ],
       [0.37, 0.49, 0.19, 0.  , 0.  ],
       [0.38, 0.59, 0.1 , 0.  , 1.  ],
       [0.47, 0.54, 0.56, 0.  , 1.  ],
       [0.14, 0.34, 0.31, 0.  , 1.  ],
       [0.46, 0.48, 0.63, 0.  , 1.  ],
       [0.09, 0.58, 0.08, 1.  , 0.  ],
       [0.73, 0.74, 0.66, 1.  , 0.  ],
       [0.56, 0.64, 0.54, 0.  , 1.  ],
       [0.39, 0.67, 0.29, 0.  , 1.  ],
       [0.8 , 0.37, 0.77, 1.  , 0.  ],
       [0.57, 0.71, 0.6 , 1.  , 0.  ],
       [0.17, 0.51, 0.37, 0.  , 1.  ],
       [0.  , 0.5 , 0.1 , 0.  , 1.  ],
       [0.98, 0.76, 0.94, 0.  , 1.  ],
       [0.57, 0.58, 0.53,

In [43]:
#import model

from sklearn .linear_model import LinearRegression

regressor=LinearRegression()
regressor.fit(x_train,y_train)




LinearRegression()

In [44]:
#examine data


y_pred=regressor.predict(x_test)
np.set_printoptions(precision=2)
arr= np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)
arr

array([[103015.2 , 103282.38],
       [132582.28, 144259.4 ],
       [132447.74, 146121.95],
       [ 71976.1 ,  77798.83],
       [178537.48, 191050.39],
       [116161.24, 105008.31],
       [ 67851.69,  81229.06],
       [ 98791.73,  97483.56],
       [113969.44, 110352.25],
       [167921.07, 166187.94]])

In [45]:
(arr[:,0]-arr[:,1]).sum()

-39520.102448097794